GROUP_TYPES = (
    'LightGroup',
    'Room',
)

ALLOWED_ROOM_CLASSES = (
    'Living room',
    'Kitchen',
    'Dining',
    'Bedroom',
    'Kids bedroom',
    'Bathroom',
    'Nursery',
    'Recreation',
    'Office',
    'Gym',
    'Hallway',
    'Toilet',
    'Front door',
    'Garage',
    'Terrace',
    'Garden',
    'Driveway',
    'Carport',
    'Other',  # default
    'Home',
    'Downstairs',
    'Upstairs',
    'Top floor',
    'Attic',
    'Guest room',
    'Staircase',
    'Lounge',
    'Man cave',
    'Computer',
    'Studio',
    'Music',
    'TV',
    'Reading',
    'Closet',
    'Storage',
    'Laundry room',
    'Balcony',
    'Porch',
    'Barbecue',
    'Pool',
)
